### ISSUE TITLE
Pandas Dependency 0.6.1

### ISSUE THREAD

**Issue by charlieort12** [ahnazary/stockdex#12]
Failure to run 0.6.1, meaning for example TickerFactory rather than Ticker must be used. This is due to a dependence on Pandas 2.2.0 which as far as I can tell is still in pre-release stage. Keen for any help, thanks.

**Comment by ahnazary** [comment]
Can you send the full error message as well and some steps on how to reproduce it?

**Comment by ahnazary** [comment]
`TickerFactory` is deprecated in the newer version. Follow the docs for more details.
